### ISSUE TITLE
🍃 Configurar ambiente Spring

### ISSUE THREAD

**Issue by RogerSouza1** [RogerSouza1/e-commerce-vinicola#21]
Necessário configurar o ambiente Spring para inicializar o desenvolvimento geral:

- [x] Injetar as dependências necessárias para o projeto
- [x] Definir como funcionará o banco de dados (H2, MySQL, Spring JPA, etc.)
- [x] Realizar o padrão de arquitetura MVC (Model - View - Controller) (Ex: https://www.inf.ufpr.br/andrey/ci163/MVC.pdf)
- [x] Realizar configuração da Landing Page (Criar página HTML e assegurar seu funcionamento)

Dica: Pelo bem geral do grupo, tanto físico quando mental, sugiro que seja definido ferramentas que todos tenho total entendimento e facilidade no manuseio delas, caso seja algo muito complexo, talvez a curva de aprendizado inicial seja muito grande. Tendo em vista isso, vamos decidir um bom framework e modo de trabalho que seja escalável e eficiente e que não tenha uma curva de aprendizado muito demorada.

OBS: Coloque sempre referência das ferramente para todos estarem a parte de como ela funciona (Ex: Documentação do Spring WEB, Lombok, MVC, etc.)

**Comment by Pelifefe** [comment]
Configurações na dependência JPA:

aplication properties:  
spring.jpa.hibernate.ddl-auto=update
Motivo: Controla como o Hibernate gerencia o esquema do banco de dados. update cria ou atualiza o esquema automaticamente com base nas entidades JPA. 
O que é?: Essa configuração diz ao Spring Boot para criar ou atualizar as tabelas no banco de dados automaticamente com base nas classes que você definiu no seu código. Se você criar uma nova classe (ou seja, uma nova "tabela"), ela será automaticamente criada no banco de dados H2 na próxima vez que você rodar a aplicação
Por que é útil?: Você não precisa se preocupar em criar as tabelas manualmente. O Spring Boot cuida disso, permitindo que você se concentre no desenvolvimento do seu código.

class Usuario:
Com base nas dependências e no contexto do projeto, a recomendação seria usar GenerationType.IDENTITY ao invés do GenerationType.AUTO. Isso porque:
Simplicidade: O banco de dados gerencia a geração dos IDs, o que simplifica a configuração.
Compatibilidade: O H2 Database suporta colunas auto-incremento, o que é ideal para desenvolvimento e testes.
Desempenho: Pode ser mais eficiente, pois evita a necessidade de uma tabela separada para gerenciar a sequência de IDs.

**Comment by Pelifefe** [comment]
Dependências definidas atualmente para o desenvolvimento do e-commerce:
- Spring Boot Dev tools
- Lombok
- Spring Web
- Validation
- Spring Data JPA
- H2 database
- Spring security
- Spring session
- Thymeleaf
- Thymeleaf extras
